In [1]:
import numpy as np

In [2]:
a = [3, 4, 6]

In [3]:
arreglo_a = np.array(a)

In [4]:
arreglo_a

array([3, 4, 6])

In [5]:
print(arreglo_a)

[3 4 6]


In [6]:
arreglo_b = np.array([5.6, 5.1, 7.4])

In [7]:
arreglo_b

array([5.6, 5.1, 7.4])

In [13]:
valor = arreglo_b[1,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [14]:
vector = np.array([1,2,3,4,5,6,7,8,9,10])

In [15]:
vector.size

10

In [16]:
vector.shape

(10,)

In [20]:
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
vectorA = np.ones(100, dtype=int)
vectorB = np.ones(100, dtype=int)
vectorC = vectorA.dot(vectorB)
normaVector = np.linalg.norm(vectorA)
print(vectorC)
print(normaVector)

100
10.0


In [51]:
# Matrices
matrixA = np.array([[1,2,3],
                    [5,6,7],
                    [8,9,10]])



In [61]:
determinante = np.linalg.det(matrixA)
determinante

2.914335439641041e-16

In [63]:
trazaA = np.trace(matrixA)
trazaA

17

In [65]:
inversa = np.linalg.inv(matrixA)
inversa

array([[-1.0293942e+16,  2.4019198e+16, -1.3725256e+16],
       [ 2.0587884e+16, -4.8038396e+16,  2.7450512e+16],
       [-1.0293942e+16,  2.4019198e+16, -1.3725256e+16]])

In [59]:
matrixB = np.ones((3,3), dtype=int)
matrixB

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [66]:
matrixB = np.zeros((3,3), dtype=int)


In [67]:
matrixA

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [74]:
matrixA[1,1]

array([2, 6, 9])

In [81]:
matrixA = np.ones((3,3))
matrixB = 2*np.ones((3,3))
print(matrixB)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [83]:
matrixA.dot(matrixB)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [84]:
np.dot(matrixA, matrixB)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])