In [1]:
import numpy as np
import time

In [2]:
def measure_execution_time(func, *args, **kwargs):
    """
    Mide el tiempo de ejecución de una función.

    :param func: La función a medir.
    :param args: Los argumentos posicionales para la función.
    :param kwargs: Los argumentos de palabra clave para la función.
    :return: El tiempo de ejecución en segundos.
    """
    start_time = time.time()  # Marca el inicio del tiempo
    func(*args, **kwargs)  # Ejecuta la función con los argumentos dados
    end_time = time.time()  # Marca el final del tiempo
    
    execution_time = end_time - start_time  # Calcula el tiempo de ejecución
    print(f"Tiempo de ejecución: {execution_time:.6f} segundos")

    return execution_time

## Midpoint Rule

In [3]:
# Midpoint
a = 0
b = 1
m = 3
h = (b - a) / m
mp1 = np.arange(a + h/2, b, h)
print(mp1)
mp2 = np.linspace(a + h/2, b - h/2, m)
print(mp2)
mp3 = np.array([a + k*h + h/2 for k in range(0,m)])
print(mp3)

[0.16666667 0.5        0.83333333]
[0.16666667 0.5        0.83333333]
[0.16666667 0.5        0.83333333]


In [4]:
midpoints = np.zeros(m)
for i in range(m):
    midpoints[i] = (2 * i + 1) * h / 2
midpoints

array([0.16666667, 0.5       , 0.83333333])

## Trapezoidal Rule

In [5]:
def fun_list_comprehension(a,h,m):
    return np.array([a + k * h for k in range(0,m+1)])

In [6]:
# Trapezoidal
a = 0
b = 1
m = 3
h = (b - a) / m
g = np.arange(a, b+h, h)
print(g)
j = np.linspace(a,b,m+1)
print(j)
# f = np.array([a + k * h for k in range(m+1)])
f = fun_list_comprehension(a,h,m)
print(f)

[0.         0.33333333 0.66666667 1.        ]
[0.         0.33333333 0.66666667 1.        ]
[0.         0.33333333 0.66666667 1.        ]


### Tiempo de ejecución para creación de arreglos

In [7]:
measure_execution_time(np.arange, a,b,h)
measure_execution_time(np.linspace, a,b,m+1)
measure_execution_time(fun_list_comprehension, a,h,m)

Tiempo de ejecución: 0.000012 segundos
Tiempo de ejecución: 0.000049 segundos
Tiempo de ejecución: 0.000006 segundos


6.4373016357421875e-06

## Simpson's Rule

In [9]:
# simpson
a = 0
b = 1
m = 10
h = (b - a) / m
H = h / 3
xi = np.array([a + i * h for i in range(0,m+1)])
xi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
# xi[np.arange(1,m+1,2)]
xi[1:m+1:2]

array([0.1, 0.3, 0.5, 0.7, 0.9])

In [10]:
# xi[np.arange(2,m,2)]
xi[2:m:2]

array([0.2, 0.4, 0.6, 0.8])